javascript-bank | Kianna Brandt
KiannaBrandt/m2-0321-code-solutions pull request #5
Opened 2021-03-11 05:35 UTC by KiannaBrandt

2021-03-11 23:45 UTC, TimelikeClosure requested changes
@KiannaBrandt Please include a screenshot(s) of your successful test output in the pull request.

2021-03-12 00:28 UTC, KiannaBrandt commented
<img width="1113" alt="Screen Shot 2021-03-11 at 3 46 00 PM" src="https://user-images.githubusercontent.com/69865999/110870393-31a1a000-8281-11eb-846e-5c8143bbc371.png">

2021-03-12 03:58 UTC, TimelikeClosure requested changes

2021-03-12 03:58 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +  for (i = 0; i < this.accounts.length; i++) {
Please declare all your variables before using them.

2021-03-12 03:58 UTC, TimelikeClosure commented on javascript-bank/bank.js
> +  for (i = 0; i < this.accounts.length; i++) {
Same as above.

2021-03-12 04:02 UTC, TimelikeClosure approved these changes

2021-03-12 04:02 UTC, merged